 version: '2'
 services:
  server:
   image: node:6.11.4
   working_dir: /code
   volumes:
    - '.:/code'
    - '~/.ssh/id_rsa:/root/.ssh/id_rsa'
   command: bash -c "tail -f /dev/null"
   ports:
    - '6969:6969'
   depends_on:
     - mongodb
  mongodb:
   image: mongo:2.4.10
   command: mongod --rest
   ports:
    - '27017:27017'
