 version: '2'
 services:
  server:
   image: node:6.11.4
   working_dir: /code
   volumes:
    - '.:/code'
    - '~/.ssh/id_rsa:/root/.ssh/id_rsa'
   command: bash -c "npm start"
   ports:
    - '6969:6969'
   depends_on:
     - mongodb
     - mosquitto
  mongodb:
   image: mongo:2.4.10
   command: mongod --rest
   ports:
    - '27017:27017'
  mosquitto:
    image: eclipse-mosquitto
    working_dir: /mosquitto
    volumes:
      - './mosquitto.conf:/mosquitto/config/mosquitto.conf'
    ports:
      - '1883:1883'
